version: '3.8'

services:
  postgres:
    build:
      context: .
      dockerfile: Dockerfile.db
    command: '-c logging_collector=on -c log_directory=logs -c log_statement=all -p ${POSTGRES_PORT}'
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    restart: always
    env_file:
      - .env
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - my-network

  pgadmin:
    image: dpage/pgadmin4
    env_file:
      - .env
    ports:
      - ${PGADMIN_PORT}:${PGADMIN_PORT}
    restart: always
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    networks:
      - my-network

  backend:
    depends_on:
      - postgres
    build:
      context: .
      dockerfile: Dockerfile.app
    ports:
      - ${BACKEND_PORT}:${BACKEND_PORT}
    restart: always
    env_file:
      - .env
    volumes:
      - backend-data:/app
      - ./src:/app/src
    networks:
      - my-network

volumes:
  postgres-data:
  backend-data:
  pgadmin-data:

networks:
  my-network:
    driver: bridge
