version: '3.8'

services:
  postgres:
    build:
      context: .
      dockerfile: Dockerfile.db
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    restart: always
    env_file:
      - .env
    volumes:
      - db-data:/var/lib/postgresql/data
      - db-data:/var/log/postgresql
    networks:
      - my-network

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    env_file:
      - .env
    ports:
      - ${PGADMIN_PORT}:${PGADMIN_PORT}
    networks:
      - my-network

  backend:
    depends_on:
      - postgres
    build:
      context: .
      dockerfile: Dockerfile.app
    ports:
      - ${BACKEND_PORT}:${BACKEND_PORT}
    restart: always
    env_file:
      - .env
    volumes:
      - backend-data:/app/data
      - ./src:/app/src
    networks:
      - my-network

volumes:
  backend-data:
  db-data:

networks:
  my-network:
    driver: bridge
